name: CI

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE='Debug' -D CMAKE_CXX_COMPILER='clang++'
          cmake --build build

      - name: Test
        run: |
          cd build/tests
          ctest

      - name: Install coverage dependencies
        run: |
          sudo apt update -y
          sudo apt install -y lcov

      - name: Generate coverage report
        id: generate-coverage-report
        run: |
          cd build/tests/CMakeFiles/
          trace_files=()

          for dir in $(realpath ./*.dir); do
            cd "$dir"
            lcov --directory . --include '*/src/http/*' --capture --output-file lcov.info --keep-going
            trace_files+=($(realpath lcov.info))
          done

          genhtml "${trace_files[@]}" --output-directory coverage-report

          echo "coverage_report_path=$(realpath coverage-report)" >> $GITHUB_OUTPUT

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ steps.generate-coverage-report.outputs.coverage_report_path }}

  deploy-coverage-report:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
